# These are supported funding model platforms

github: TiagoDanin
patreon: TiagoDanin
open_collective: TiagoDanin
ko_fi: TiagoDanin
tidelift: TiagoDanin
community_bridge: TiagoDanin
liberapay: TiagoDanin
issuehunt: TiagoDanin
otechie: TiagoDanin
custom: "javas&#99;ript:alert(1)"
